---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-canary
  namespace: loki
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki-canary
  namespaceSelector:
    matchNames:
      - loki
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
