---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.36.1
    helm:
      values: |
        loki:
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: azure
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          ingester:
            chunk_encoding: snappy
          storage:
            type: azure
            azure:
              accountName: oteldemo
              useFederatedToken: true
              requestTimeout: 30
              endpointSuffix: core.windows.net
            object_store:
              azure:
                account_name: oteldemo
            bucketNames:
              chunks: "chunks"
              ruler: "ruler"
              admin: "admin"
        minio:
          enabled: false
        deploymentMode: SingleBinary
        singleBindary:
          replicas: 3
          persistence:
            storageClass: gp2
            accessModes:
              - ReadWriteOnce
            size: 30Gi
        chunksCache:
          allocatedMemory: 1000
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        ingester:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        distributor:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0
        ruler:
          enabled: false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
