---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.38.0
    helm:
      valuesObject:
        loki:
          auth_enabled: false
          podLabels:
            "azure.workload.identity/use": "true"
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: azure
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage_config:
            azure:
              account_name: "SHOULD BE REPLACED"
              container_name: "SHOULD BE REPLACED"
              use_federated_token: true
          ingester:
            chunk_encoding: snappy
          pattern_ingester:
            enabled: true
          limits_config:
            allow_structured_metadata: true
            volume_enabled: false
            retention_period: 672h  # 28 days retention
          compactor:
            retention_enabled: true
            delete_request_store: azure
          ruler:
            enable_api: true
            storage:
              type: azure
              azure:
                account_name: "SHOULD BE REPLACED"
                container_name: "SHOULD BE REPLACED"
                use_federated_token: true
              alertmanager_url: http://prom:9093
          querier:
             max_concurrent: 4
          storage:
            type: azure
            bucketNames:
              chunks: "SHOULD BE REPLACED"
              ruler: "SHOULD BE REPLACED"
            azure:
              accountName: "SHOULD BE REPLACED"
              useFederatedToken: true
        serviceAccount:
          name: loki
          annotations:
            "azure.workload.identity/client-id": "SHOULD BE REPLACED"
          labels:
            "azure.workload.identity/use": "true"
        deploymentMode: SimpleScalable
        read:
          replicas: 3
        backend:
          replicas: 3
          persistence:
            volumeClaimsEnabled: true
        write:
          replicas: 3
          persistence:
            volumeClaimsEnabled: true
        gateway:
          enabled: true
        minio:
          enabled: false
        chunksCache:
          allocatedMemory: 1000
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
