---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.36.1
    helm:
      values: |
        loki:
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: azure
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          ingester:
            chunk_encoding: snappy
          tracing:
            enabled: true
          querier:
            max_concurrent: 4
          storage:
            type: azure
            azure:
              accountName: oteldemo
              useFederatedToken: true
              requestTimeout: 30
              endpointSuffix: core.windows.net
            bucketNames:
              chunks: "chunks"
              ruler: "ruler"
              admin: "admin"
        deploymentMode: SimpleScalable
        ingester:
          replicas: 3
          zoneAwareReplication:
            enabled: false
        querier:
          replicas: 3
          maxUnavailable: 2
        queryFrontend:
          replicas: 2
          maxUnavailable: 1
        queryScheduler:
          replicas: 2
        distributor:
          replicas: 3
          maxUnavailable: 2
        compactor:
          replicas: 1
        indexGateway:
          replicas: 2
          maxUnavailable: 1
        bloomPlanner:
          replicas: 0
        bloomBuilder:
          replicas: 0
        bloomGateway:
          replicas: 0
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        singleBinary:
          replicas: 0
        chunksCache:
          enabled: false            # or leave as-is (it’s enabled by default)
        resultsCache:
          enabled: false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
