---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.37.0
    helm:
      values: |
        loki:
          podLabels:
            "azure.workload.identity/use": "true"
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: azure
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage_config:
            azure:
              account_Name: "oteldemo"
              container_name: "chunks"
              use_federated_token: true
          ingester:
            chunk_encoding: snappy
          pattern_ingester:
            enabled: true
          limits_config:
            allow_structured_metadata: true
            volume_enabled: true
            retention_period: 672h # 28 days retention
          compactor:
            retention_enabled: true
            delete_request_store: azure
          ruler:
            enable_api: true
            storage:
              type: azure
              azure:
                account_name: oteldemo
                container_name: ruler
                use_federated_token: true
              alertmanager_url: http://prom:9093
          querier:
             max_concurrent: 4
          storage:
            type: azure
            bucketNames:
              chunks: "chunks"
              ruler: "ruler"
            azure:
              accountName: oteldemo
              useFederatedToken: true
        serviceAccount:
          name: loki
          annotations:
            "azure.workload.identity/client-id": "16b6ae75-279d-4ebb-ab69-dfeb135eaee8"
          labels:
            "azure.workload.identity/use": "true"
        deploymentMode: SingleBinary
        gateway:
          enabled: false
        minio:
          enabled: false
        singleBinary:
          replicas: 3
        chunksCache:
          allocatedMemory: 1000
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        ingester:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        distributor:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
