---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: tempo
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo-distributed
    targetRevision: 1.47.2
    helm:
      valuesObject:
        global:
          podLabels:
            "azure.workload.identity/use": "true"
        extraEnv:
          - name: AZURE_CLIENT_ID
            value: 41e5a552-bbe9-4ec0-8733-47df49e7f7c3
        storage:
          trace:
            backend: azure
            azure:
              container_name: traces
              storage_account_name: opentelemtrydemostorage
              use_federated_token: true
        traces:
          otlp:
            grpc:
              enabled: true
        serviceAccount:
          name: tempo
          annotations:
            "azure.workload.identity/client-id": "SHOULD BE REPLACED"
          labels:
            "azure.workload.identity/use": "true"
            compactor:
        ingester:
          extraEnv:
            - name: AZURE_CLIENT_ID
              value: 41e5a552-bbe9-4ec0-8733-47df49e7f7c3
        distributor:
          extraEnv:
            - name: AZURE_CLIENT_ID
              value: 41e5a552-bbe9-4ec0-8733-47df49e7f7c3
        querier:
          extraEnv:
            - name: AZURE_CLIENT_ID
              value: 41e5a552-bbe9-4ec0-8733-47df49e7f7c3
        queryFrontend:
          extraEnv:
            - name: AZURE_CLIENT_ID
              value: 41e5a552-bbe9-4ec0-8733-47df49e7f7c3
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
